# Uncomment this line to define a global platform for your project
# platform :ios, '17.0'

target 'OasisBio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OasisBio
  # pod 'Alamofire'
  # pod 'Kingfisher'
  # pod 'SwiftUIX'

end
