name: Android CI

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.2

      - name: Build with Gradle
        run: |
          cd apps/android
          ./gradlew assembleRelease --no-daemon

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: apps/android/app/build/outputs/apk/release/app-release.apk